### PR TITLE
fix: ignore no-redeclare, no-namespace

### LINKED ISSUE #11: fix: disable no-namespace
sorry but I discussed it last night....
also no-duplicate maybe
@sunrabbit123 if you have time please contribute it!

### PR DESCRIPTION
**Pull request by sunrabbit123**
This pull request includes changes to the TypeScript configuration in the `wrtnlabs` function within the `src/index.ts` file. The most important change involves commenting out two ESLint rules and adding a reference to an issue in the `wrtnlabs` repository.

Configuration changes:

* [`src/index.ts`](diffhunk://#diff-a2a171449d862fe29692ce031981047d7ab755ae7f84c707aef80701b3ea0c80L17-R20): Commented out the `ts/no-redeclare` and `ts/no-namespace` ESLint rules and added a reference to issue #11 in the `wrtnlabs` repository.

### CODE REVIEW

**Comment by ryoppippi** [comment]
Temporarily we'll do it thanks!

**Review by ryoppippi — APPROVED** [review]
LGTM

**Comment by ryoppippi** [comment]
let's merge it and release it

File: src/index.ts [hunk 1]
```diff
@@ -14,8 +14,9 @@ export async function wrtnlabs(options: UserOptions, ...args: UserConfigs[]): Pr
     typescript: {
       tsconfigPath,
       overrides: {
-        "ts/no-redeclare": "warn", // for type hierarchy structure(ex: ChatCompletion.Choice)
-        "ts/no-namespace": "warn", // namespace is not recommended, but we have a lot of namespaces, so now we just warn
+        // ref: https://github.com/wrtnlabs/eslint-config/issues/11
+        "ts/no-redeclare": "off", // for type hierarchy structure(ex: ChatCompletion.Choice)
+        "ts/no-namespace": "off", // namespace is not recommended, but we have a lot of namespaces, so now we just warn
```
Comment (ryoppippi) [inline src/index.ts:19]: need fixing this commet as well?

Comment (sunrabbit123) [reply src/index.ts:19]: What comments have been changed?
I just add the ref link about changed reason
